using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CryptoWidget.BLL.Models
{
    public class Rates
    {
        public double ABC { get; set; }
        public double ACP { get; set; }
        public double ACT { get; set; }
        public double ADA { get; set; }
        public double ADCN { get; set; }
        public double ADL { get; set; }
        public double ADX { get; set; }
        public double ADZ { get; set; }
        public double AE { get; set; }
        public int AGI { get; set; }
        public double AIB { get; set; }
        public double AIDOC { get; set; }
        public double AION { get; set; }
        public double AIR { get; set; }
        public double ALT { get; set; }
        public double AMB { get; set; }
        public double AMM { get; set; }
        public double ANT { get; set; }
        public double APC { get; set; }
        public double APPC { get; set; }
        public double ARC { get; set; }
        public double ARCT { get; set; }
        public double ARDR { get; set; }
        public double ARK { get; set; }
        public double ARN { get; set; }
        public double ASAFE2 { get; set; }
        public double AST { get; set; }
        public double ATB { get; set; }
        public double ATM { get; set; }
        public double AURS { get; set; }
        public double AVT { get; set; }
        public double BAR { get; set; }
        public double BASH { get; set; }
        public double BAT { get; set; }
        public double BAY { get; set; }
        public double BBP { get; set; }
        public double BCD { get; set; }
        public double BCH { get; set; }
        public double BCN { get; set; }
        public double BCPT { get; set; }
        public double BEE { get; set; }
        public double BIO { get; set; }
        public double BLC { get; set; }
        public double BLOCK { get; set; }
        public double BLU { get; set; }
        public double BLZ { get; set; }
        public double BMC { get; set; }
        public double BNB { get; set; }
        public double BNT { get; set; }
        public double BOST { get; set; }
        public double BQ { get; set; }
        public double BQX { get; set; }
        public double BRD { get; set; }
        public double BRIT { get; set; }
        public int BT1 { get; set; }
        public int BT2 { get; set; }
        public double BTC { get; set; }
        public double BTCA { get; set; }
        public double BTCS { get; set; }
        public int BTCZ { get; set; }
        public double BTG { get; set; }
        public int BTLC { get; set; }
        public double BTM { get; set; }

        public double BTQ { get; set; }
        public double BTS { get; set; }
        public double BTX { get; set; }
        public double BURST { get; set; }
        public double CALC { get; set; }
        public double CAS { get; set; }
        public double CAT { get; set; }
        public double CCRB { get; set; }
        public double CDT { get; set; }
        public double CESC { get; set; }
        public double CHAT { get; set; }
        public double CJ { get; set; }
        public double CL { get; set; }
        public double CLD { get; set; }
        public int CLOAK { get; set; }
        public double CND { get; set; }
        public double CNX { get; set; }
        public double CPC { get; set; }
        public double CRAVE { get; set; }
        public double CRC { get; set; }
        public double CRE { get; set; }
        public double CRW { get; set; }
        public double CTO { get; set; }
        public double CTR { get; set; }
        public double CVC { get; set; }
        public double DAS { get; set; }
        public double DASH { get; set; }
        public double DAT { get; set; }
        public int DATA { get; set; }
        public double DBC { get; set; }
        public double DBET { get; set; }
        public double DCN { get; set; }
        public double DCR { get; set; }
        public double DCT { get; set; }
        public double DEEP { get; set; }
        public double DENT { get; set; }
        public double DGB { get; set; }
        public double DGD { get; set; }
        public double DIM { get; set; }
        public double DIME { get; set; }
        public double DMD { get; set; }
        public double DNT { get; set; }
        public double DOGE { get; set; }
        public double DRGN { get; set; }
        public int DRZ { get; set; }
        public double DSH { get; set; }
        public double DTA { get; set; }
        public int EC { get; set; }
        public double EDG { get; set; }
        public double EDO { get; set; }
        public double EDR { get; set; }
        public double EKO { get; set; }
        public double ELA { get; set; }
        public double ELF { get; set; }
        public double EMC { get; set; }
        public double EMGO { get; set; }
        public double ENG { get; set; }
        public double ENJ { get; set; }
        public double EOS { get; set; }
        public double ERT { get; set; }
        public double ETC { get; set; }
        public double ETH { get; set; }
        public double ETN { get; set; }
        public double ETP { get; set; }
        public double ETT { get; set; }
        public double EVR { get; set; }
        public double EVX { get; set; }
        public double FCT { get; set; }
        public double FLP { get; set; }
        public double FOTA { get; set; }
        public double FRST { get; set; }
        public double FUEL { get; set; }
        public double FUN { get; set; }
        public double FUNC { get; set; }
        public double FUTC { get; set; }
        public double GAME { get; set; }
        public double GAS { get; set; }
        public double GBYTE { get; set; }
        public double GMX { get; set; }
        public double GNO { get; set; }
        public double GNT { get; set; }
        public double GNX { get; set; }
        public double GRC { get; set; }
        public int GRS { get; set; }
        public int GRWI { get; set; }
        public double GTC { get; set; }
        public double GTO { get; set; }
        public double GUP { get; set; }
        public double GVT { get; set; }
        public double GXS { get; set; }
        public double HAC { get; set; }
        public int HNC { get; set; }
        public double HSR { get; set; }
        public double HST { get; set; }
        public double HVN { get; set; }
        public double ICN { get; set; }
        public int ICOS { get; set; }
        public double ICX { get; set; }
        public double IGNIS { get; set; }
        public double ILC { get; set; }
        public double INK { get; set; }
        public double INS { get; set; }
        public double INSN { get; set; }
        public double INT { get; set; }
        public double IOP { get; set; }
        public double IOST { get; set; }
        public double ITC { get; set; }
        public double KCS { get; set; }
        public double KICK { get; set; }
        public double KIN { get; set; }
        public double KLC { get; set; }
        public double KMD { get; set; }
        public double KNC { get; set; }
        public int KRB { get; set; }
        public double LA { get; set; }
        public double LEND { get; set; }
        public double LEO { get; set; }
        public double LINDA { get; set; }
        public double LINK { get; set; }
        public double LOC { get; set; }
        public double LOG { get; set; }
        public double LRC { get; set; }
        public double LSK { get; set; }
        public double LTC { get; set; }
        public double LUN { get; set; }
        public double LUX { get; set; }
        public double MAID { get; set; }
        public double MANA { get; set; }
        public double MCAP { get; set; }
        public double MCO { get; set; }
        public double MDA { get; set; }
        public double MDS { get; set; }
        public double MIOTA { get; set; }
        public double MKR { get; set; }
        public double MLN { get; set; }
        public double MNX { get; set; }
        public double MOD { get; set; }
        public double MOIN { get; set; }
        public double MONA { get; set; }
        public double MTL { get; set; }
        public double MTX { get; set; }
        public double NAS { get; set; }
        public double NAV { get; set; }
        public double NBT { get; set; }
        public double NDC { get; set; }
        public double NEBL { get; set; }
        public double NEO { get; set; }
        public double NEU { get; set; }
        public double NEWB { get; set; }
        public double NGC { get; set; }
        public double NKC { get; set; }
        public double NLC2 { get; set; }
        public double NMC { get; set; }
        public double NMR { get; set; }
        public double NULS { get; set; }
        public int NVC { get; set; }
        public double NXT { get; set; }
        public double OAX { get; set; }
        public double OBITS { get; set; }
        public double OC { get; set; }
        public double OCN { get; set; }
        public double ODN { get; set; }
        public double OK { get; set; }
        public double OMG { get; set; }
        public double OMNI { get; set; }
        public int ORE { get; set; }
        public double ORME { get; set; }
        public double OST { get; set; }
        public int OTN { get; set; }
        public double OTX { get; set; }
        public double OXY { get; set; }
        public double PART { get; set; }
        public double PAY { get; set; }
        public double PBT { get; set; }
        public double PCS { get; set; }
        public double PIVX { get; set; }
        public double PIZZA { get; set; }
        public int PLBT { get; set; }
        public double PLR { get; set; }
        public double POE { get; set; }
        public double POLY { get; set; }
        public double POSW { get; set; }
        public double POWR { get; set; }
        public double PPC { get; set; }
        public double PPT { get; set; }
        public double PPY { get; set; }
        public double PRC { get; set; }
        public double PRES { get; set; }
        public double PRG { get; set; }
        public double PRL { get; set; }
        public double PRO { get; set; }
        public double PURA { get; set; }
        public int PUT { get; set; }
        public double QASH { get; set; }
        public int QAU { get; set; }
        public double QSP { get; set; }
        public double QTUM { get; set; }
        public double QUN { get; set; }
        public double R { get; set; }
        public int RBIES { get; set; }
        public double RCN { get; set; }
        public double RDD { get; set; }
        public int RDN { get; set; }
        public double REBL { get; set; }
        public double REE { get; set; }
        public double REP { get; set; }
        public double REQ { get; set; }
        public double REV { get; set; }
        public double RGC { get; set; }
        public double RHOC { get; set; }
        public double RIYA { get; set; }
        public int RKC { get; set; }
        public double RLC { get; set; }
        public double RPX { get; set; }
        public double RUFF { get; set; }
        public double SALT { get; set; }
        public double SAN { get; set; }
        public int SBC { get; set; }
        public double SC { get; set; }
        public double SENT { get; set; }
        public int SHIFT { get; set; }
        public double SIB { get; set; }
        public double SMART { get; set; }
        public double SMLY { get; set; }
        public double SNC { get; set; }
        public double SNGLS { get; set; }
        public double SNM { get; set; }
        public double SNT { get; set; }
        public double SPK { get; set; }
        public double SRN { get; set; }
        public double STEEM { get; set; }
        public double STK { get; set; }
        public double STORJ { get; set; }
        public double STRAT { get; set; }
        public double STU { get; set; }
        public double STX { get; set; }
        public double SUB { get; set; }
        public double SUR { get; set; }
        public double SWFTC { get; set; }
        public double SYS { get; set; }
        public int TAAS { get; set; }
        public double TESLA { get; set; }
        public double THC { get; set; }
        public double THETA { get; set; }
        public double THS { get; set; }
        public double TIO { get; set; }
        public int TKN { get; set; }
        public double TKY { get; set; }
        public double TNB { get; set; }
        public double TNT { get; set; }
        public double TOA { get; set; }
        public double TRC { get; set; }
        public double TRIG { get; set; }
        public double TRST { get; set; }
        public double TRUMP { get; set; }
        public double TRX { get; set; }
        public double UBQ { get; set; }
        public double UNO { get; set; }
        public double UNRC { get; set; }
        public int UQC { get; set; }
        public double USDT { get; set; }
        public double UTK { get; set; }
        public double UTT { get; set; }
        public double VEE { get; set; }
        public double VEN { get; set; }
        public double VERI { get; set; }
        public double VIA { get; set; }
        public double VIB { get; set; }
        public double VIBE { get; set; }
        public double VOISE { get; set; }
        public double VOX { get; set; }
        public double VRS { get; set; }
        public double VTC { get; set; }
        public double VUC { get; set; }
        public double WABI { get; set; }
        public double WAVES { get; set; }
        public double WAX { get; set; }
        public double WC { get; set; }
        public double WGR { get; set; }
        public double WINGS { get; set; }
        public double WLK { get; set; }
        public double WOP { get; set; }
        public double WPR { get; set; }
        public double WRC { get; set; }
        public double WTC { get; set; }
        public double XAUR { get; set; }
        public double XBP { get; set; }
        public double XBY { get; set; }
        public double XCP { get; set; }
        public double XCXT { get; set; }
        public double XDN { get; set; }
        public double XEM { get; set; }
        public double XGB { get; set; }
        public double XHI { get; set; }
        public double XID { get; set; }
        public double XLM { get; set; }
        public double XMR { get; set; }
        public double XNC { get; set; }
        public double XRB { get; set; }
        public double XRP { get; set; }
        public double XTO { get; set; }
        public double XTZ { get; set; }
        public double XUC { get; set; }
        public double XVG { get; set; }
        public double XZC { get; set; }
        public double YEE { get; set; }
        public double YOC { get; set; }
        public double YOYOW { get; set; }
        public double ZBC { get; set; }
        public double ZCL { get; set; }
        public double ZEC { get; set; }
        public double ZEN { get; set; }
        public double ZIL { get; set; }
        public double ZNY { get; set; }
        public double ZRX { get; set; }
        public double ZSC { get; set; }
    }
}
